<?php
/**
 * One Pica
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to codemaster@onepica.com so we can send you a copy immediately.
 * 
 * @category    PlanetPayment
 * @package     PlanetPayment_Upop
 * @copyright   Copyright (c) 2012 Planet Payment Inc. (http://www.planetpayment.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Planet Payment
 *
 * @category   PlanetPayment
 * @package    PlanetPayment_Upop
 * @author     One Pica Codemaster <codemaster@onepica.com>
 */
?>
<div id="checkout-currency_selector-load">
    <form id="co-currency-select-form" action="">
        <fieldset>
            <?php if ($this->hasOptions()): ?>
                <dl>
                    <dt>
                    <div><em><?php echo $this->__("As a convenience to our international customers, your purchase can be completed in your home currency at today's exchange rate of ".$this->getExchangeRate()." (Wholesale Rate ".$this->getMarkUp()."%).");?></em></div>
                    <div><?php echo $this->__("Select One Currency for your payment:");?></div>
                    </dt>
                    <?php
                    $_options = $this->getCurrencyOptions();
                    foreach ($_options as $key => $value):
                        ?>
                        <dd>
                            <input type="radio" name="payment[selected_currency]" class="validate-one-required-by-name currencies" value="<?php echo $key; ?>"/> <?php echo $value; ?> 
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
        </fieldset>
    </form>


    <div id="currency_select-buttons-container" class="buttons-set" style="">
        <p class="required">* Required Fields</p>
        <p class="back-link"><a onclick="checkout.back(); return false;" href="#"><small><<</small>Back</a></p>
        <button onclick="currencySelect.save()" class="button" type="button"><span><span>Continue</span></span></button>
        <span style="display: none;" id="currency_select-please-wait" class="please-wait">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
        </span>
    </div>


    <script type="text/javascript">
        //<![CDATA[

        var CurrencySelect = Class.create();
        CurrencySelect.prototype = {
            initialize: function(form, saveUrl){
                this.form = form;
                if ($(this.form)) {
                    $(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
                }
                this.saveUrl = saveUrl;
                this.onSave = this.nextStep.bindAsEventListener(this);
                this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
            },

            save: function(){
                if (checkout.loadWaiting!=false) return;

                var validator = new Validation(this.form);
                if (validator.validate()) {

                    checkout.setLoadWaiting('currency_select');


                    var request = new Ajax.Request(
                    this.saveUrl,
                    {
                        method: 'post',
                        onComplete: this.onComplete,
                        onSuccess: this.onSave,
                        onFailure: checkout.ajaxFailure.bind(checkout),
                        parameters: Form.serialize(this.form)
                    }
                );
                }
            },

            resetLoadWaiting: function(transport){
                checkout.setLoadWaiting(false);
            },

            nextStep: function(transport){
                if (transport && transport.responseText){
                    try{
                        response = eval('(' + transport.responseText + ')');
                    }
                    catch (e) {
                        response = {};
                    }
                }

                if (response.error){
                    if ((typeof response.message) == 'string') {
                        alert(response.message);
                    } else {
                        if (response.update_section) {
                            $('checkout-'+response.update_section.name+'-load').update(response.update_section.html);
                        }

                        if (response.goto_section) {
                            checkout.gotoSection(response.goto_section);
                            checkout.reloadProgressBlock();
                            return;
                        }
                    }

                    return false;
                }

                checkout.setStepResponse(response);
            }    
        }

        var currencySelect = new CurrencySelect('co-currency-select-form', '<?php echo $this->getUrl('checkout/onepage/saveCurrency') ?>');

        //]]>
    </script>
</div>