<?php
/**
 * One Pica
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to codemaster@onepica.com so we can send you a copy immediately.
 * 
 * @category    PlanetPayment
 * @package     PlanetPayment_Upop
 * @copyright   Copyright (c) 2012 Planet Payment Inc. (http://www.planetpayment.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Planet Payment
 *
 * @category   PlanetPayment
 * @package    PlanetPayment_Upop
 * @author     One Pica Codemaster <codemaster@onepica.com>
 */
?>
<div id="checkout-currency_selector-load">
    <fieldset>
        <?php if ($this->hasOptions()): ?>
            <dl>
                <dt>
                <div>Select One Currency for your payment:</div>
                </dt>
                <?php
                $_options = $this->getCurrencyOptions();
                foreach ($_options as $key => $value):
                    ?>
                    <dd>
                        <input type="radio" name="payment[selected_currency]" class="validate-one-required-by-name currencies" value="<?php echo $key; ?>"/> <?php echo $value; ?> 
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
    </fieldset>
    <script type="text/javascript">
        //<![CDATA[
        $$('.currencies').each(function(e){
            Event.observe(e, 'click', updateCurrency.bind(this));
        });
            
        function updateCurrency(obj) {
            $("loading-mask").show();
            new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl('upopadmin/adminhtml_checkout/updateCurrency');?>', {
                parameters: $('edit_form').serialize(true),
                method:'post',
                onSuccess: function(transport) {
                    
                }.bind(this)
            });
        }
        //]]>
    </script>
</div>